version: '2.1'  # Balena supports version 2.1 of the Docker Compose spec
services:
  
  rpi-ros:
    build: .
    network_mode: host # use the host network to be able to communicate with the desktop
    privileged: true # enable to use GPIO pins on rpi
    # interactive mode for this container
    command: ros2 run demo_nodes_cpp talker
    stdin_open: true
    tty: true

  husarnet-zenoh:
    build: ./husarnet_zenoh
    container_name: husarnet-zenoh-bridge
    network_mode: host # necessary for zenoh-ros2 config, as docker doesn't support multicast udp
    volumes:
    - /var/lib/husarnet # persist ip address across docker restarts
    cap_add:
    - NET_ADMIN
    devices:
    - /dev/net/tun
    environment:
      # needed for husarnet
    - HUSARNET_JOIN_CODE=${COMPOSE_HUSARNET_JOIN_CODE}
    - HUSARNET_HOSTNAME=${COMPOSE_HUSARNET_HOSTNAME}
    - HUSARNET_DEBUG=1
      # needed for zenoh-dds-router
    - ROS_DISTRO=humble
    - ROS_DOMAIN_ID=${COMPOSE_ROS_DOMAIN_ID}
    stdin_open: true
    tty: true
    profiles:
      - gpu
      - nogpu

