name: operator
services:

  operator:
    container_name: operator
    build: .
    environment:
      - ROS_DOMAIN_ID=${COMPOSE_ROS_DOMAIN_ID}
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ros2 run demo_nodes_cpp listener
    stdin_open: true
    tty: true

  husarnet-zenoh-bridge:
    build: ./husarnet_zenoh
    container_name: husarnet-zenoh-bridge
    network_mode: host
    volumes:
    - /var/lib/husarnet # persist ip address across docker restarts
    cap_add:
    - NET_ADMIN
    devices:
    - /dev/net/tun
    restart: unless-stopped
    environment:
      # needed for husarnet
    - HUSARNET_JOIN_CODE=${COMPOSE_HUSARNET_JOIN_CODE}
    - HUSARNET_HOSTNAME=${COMPOSE_HUSARNET_HOSTNAME}
    - HUSARNET_DEBUG=1
      # needed for zenoh-dds-router
    - ROS_DISTRO=humble
    - ROS_DOMAIN_ID=${COMPOSE_ROS_DOMAIN_ID}
    - SERVER_NAME=${COMPOSE_SERVER_NAME}
    stdin_open: true
    tty: true

