services:

  desktop-ros:
    container_name: ${COMPOSE_CONTAINER_NAME}
    build: .
    network_mode: host # use the host network to be able to communicate with the desktop
    command: ros2 run demo_nodes_cpp talker
    environment:
      - ROS_DOMAIN_ID=0
    stdin_open: true
    tty: true

  zenoh-router:
    image: eclipse/zenoh
    network_mode: host
    restart: unless-stopped
    volumes:
    - ./zenoh_docker:/root/.zenoh
    - ./desktop-router-config.json5:/desktop-router-config.json5
    environment:
    - ROS_DISTRO=iron
    - RUST_LOG=debug
    - ROS_DOMAIN_ID=0
    depends_on:
    - husarnet-zenoh  # husarnet service is healthy if all hosts listed in WAIT_HOSTNAMES are reachable
    command: ['--config /desktop-router-config.json5']   # if needed
    stdin_open: true
    tty: true

  husarnet-zenoh:
    build: ./husarnet_zenoh
    container_name: husarnet-zenoh-bridge
    network_mode: host # necessary for zenoh-ros2 config, as docker doesn't support multicast udp
    cap_add:
    - NET_ADMIN
    devices:
    - /dev/net/tun
    environment:
      # needed for husarnet
    - HUSARNET_HOSTNAME=duke-desktop
    - HUSARNET_DEBUG=1
      # needed for zenoh-dds-router
    - ROS_DISTRO=iron
    - ROS_DOMAIN_ID=0
    stdin_open: true
    tty: true

