services:

  desktop-ros:
    build: .
    network_mode: host # use the host network to be able to communicate with the desktop
    command: ros2 run demo_nodes_cpp talker
    environment:
      - ROS_DOMAIN_ID=0
    stdin_open: true
    tty: true

  husarnet-zenoh:
    build: ./husarnet_zenoh
    container_name: husarnet-zenoh-bridge
    network_mode: host # necessary for zenoh-ros2 config, as docker doesn't support multicast udp
    cap_add:
    - NET_ADMIN
    devices:
    - /dev/net/tun
    environment:
      # needed for husarnet
    - HUSARNET_HOSTNAME=duke-rpi-host
    - HUSARNET_DEBUG=1
      # needed for zenoh-dds-router
    - ROS_DISTRO=humble
    stdin_open: true
    tty: true
